project_id = "dvwmyljnssspwfpwocof"

[functions.send-assessment-booking]
verify_jwt = false

[functions.send-business-request]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = true

[functions.subscribe-mailchimp]
verify_jwt = false

[functions.send-contact-inquiry]
verify_jwt = false

[functions.send-lp-request]
verify_jwt = false

[functions.send-gp-confirmation]
verify_jwt = false

[functions.send-call-request-notification]
verify_jwt = false

[functions.send-fundraising-report-request]
verify_jwt = false

[functions.send-adviser-campaign]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.distribute-content]
verify_jwt = true

[functions.create-bitcoin-report-checkout]
verify_jwt = false

[functions.send-abc-campaign]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false